# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ebon1/Development/perry/Cpp-Parser-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ebon1/Development/perry/Cpp-Parser-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ebon1/Development/perry/Cpp-Parser-project/CMakeFiles /home/ebon1/Development/perry/Cpp-Parser-project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ebon1/Development/perry/Cpp-Parser-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named executeme

# Build rule for target.
executeme: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executeme
.PHONY : executeme

# fast build rule for target.
executeme/fast:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/build
.PHONY : executeme/fast

Project1/AST.o: Project1/AST.cpp.o

.PHONY : Project1/AST.o

# target to build an object file
Project1/AST.cpp.o:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/AST.cpp.o
.PHONY : Project1/AST.cpp.o

Project1/AST.i: Project1/AST.cpp.i

.PHONY : Project1/AST.i

# target to preprocess a source file
Project1/AST.cpp.i:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/AST.cpp.i
.PHONY : Project1/AST.cpp.i

Project1/AST.s: Project1/AST.cpp.s

.PHONY : Project1/AST.s

# target to generate assembly for a file
Project1/AST.cpp.s:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/AST.cpp.s
.PHONY : Project1/AST.cpp.s

Project1/BinTree.o: Project1/BinTree.cpp.o

.PHONY : Project1/BinTree.o

# target to build an object file
Project1/BinTree.cpp.o:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/BinTree.cpp.o
.PHONY : Project1/BinTree.cpp.o

Project1/BinTree.i: Project1/BinTree.cpp.i

.PHONY : Project1/BinTree.i

# target to preprocess a source file
Project1/BinTree.cpp.i:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/BinTree.cpp.i
.PHONY : Project1/BinTree.cpp.i

Project1/BinTree.s: Project1/BinTree.cpp.s

.PHONY : Project1/BinTree.s

# target to generate assembly for a file
Project1/BinTree.cpp.s:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/BinTree.cpp.s
.PHONY : Project1/BinTree.cpp.s

Project1/Graph.o: Project1/Graph.cpp.o

.PHONY : Project1/Graph.o

# target to build an object file
Project1/Graph.cpp.o:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/Graph.cpp.o
.PHONY : Project1/Graph.cpp.o

Project1/Graph.i: Project1/Graph.cpp.i

.PHONY : Project1/Graph.i

# target to preprocess a source file
Project1/Graph.cpp.i:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/Graph.cpp.i
.PHONY : Project1/Graph.cpp.i

Project1/Graph.s: Project1/Graph.cpp.s

.PHONY : Project1/Graph.s

# target to generate assembly for a file
Project1/Graph.cpp.s:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/Graph.cpp.s
.PHONY : Project1/Graph.cpp.s

Project1/Node.o: Project1/Node.cpp.o

.PHONY : Project1/Node.o

# target to build an object file
Project1/Node.cpp.o:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/Node.cpp.o
.PHONY : Project1/Node.cpp.o

Project1/Node.i: Project1/Node.cpp.i

.PHONY : Project1/Node.i

# target to preprocess a source file
Project1/Node.cpp.i:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/Node.cpp.i
.PHONY : Project1/Node.cpp.i

Project1/Node.s: Project1/Node.cpp.s

.PHONY : Project1/Node.s

# target to generate assembly for a file
Project1/Node.cpp.s:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/Node.cpp.s
.PHONY : Project1/Node.cpp.s

Project1/PostFix.o: Project1/PostFix.cpp.o

.PHONY : Project1/PostFix.o

# target to build an object file
Project1/PostFix.cpp.o:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/PostFix.cpp.o
.PHONY : Project1/PostFix.cpp.o

Project1/PostFix.i: Project1/PostFix.cpp.i

.PHONY : Project1/PostFix.i

# target to preprocess a source file
Project1/PostFix.cpp.i:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/PostFix.cpp.i
.PHONY : Project1/PostFix.cpp.i

Project1/PostFix.s: Project1/PostFix.cpp.s

.PHONY : Project1/PostFix.s

# target to generate assembly for a file
Project1/PostFix.cpp.s:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/PostFix.cpp.s
.PHONY : Project1/PostFix.cpp.s

Project1/State.o: Project1/State.cpp.o

.PHONY : Project1/State.o

# target to build an object file
Project1/State.cpp.o:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/State.cpp.o
.PHONY : Project1/State.cpp.o

Project1/State.i: Project1/State.cpp.i

.PHONY : Project1/State.i

# target to preprocess a source file
Project1/State.cpp.i:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/State.cpp.i
.PHONY : Project1/State.cpp.i

Project1/State.s: Project1/State.cpp.s

.PHONY : Project1/State.s

# target to generate assembly for a file
Project1/State.cpp.s:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/State.cpp.s
.PHONY : Project1/State.cpp.s

Project1/main.o: Project1/main.cpp.o

.PHONY : Project1/main.o

# target to build an object file
Project1/main.cpp.o:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/main.cpp.o
.PHONY : Project1/main.cpp.o

Project1/main.i: Project1/main.cpp.i

.PHONY : Project1/main.i

# target to preprocess a source file
Project1/main.cpp.i:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/main.cpp.i
.PHONY : Project1/main.cpp.i

Project1/main.s: Project1/main.cpp.s

.PHONY : Project1/main.s

# target to generate assembly for a file
Project1/main.cpp.s:
	$(MAKE) -f CMakeFiles/executeme.dir/build.make CMakeFiles/executeme.dir/Project1/main.cpp.s
.PHONY : Project1/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... executeme"
	@echo "... Project1/AST.o"
	@echo "... Project1/AST.i"
	@echo "... Project1/AST.s"
	@echo "... Project1/BinTree.o"
	@echo "... Project1/BinTree.i"
	@echo "... Project1/BinTree.s"
	@echo "... Project1/Graph.o"
	@echo "... Project1/Graph.i"
	@echo "... Project1/Graph.s"
	@echo "... Project1/Node.o"
	@echo "... Project1/Node.i"
	@echo "... Project1/Node.s"
	@echo "... Project1/PostFix.o"
	@echo "... Project1/PostFix.i"
	@echo "... Project1/PostFix.s"
	@echo "... Project1/State.o"
	@echo "... Project1/State.i"
	@echo "... Project1/State.s"
	@echo "... Project1/main.o"
	@echo "... Project1/main.i"
	@echo "... Project1/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

